using System;
using System.Collections.Generic;
using System.Text;

namespace SlipeServer.Server.Elements
{
    public enum BlipIcon
    {
        Marker = 0,
        WhiteSquare = 1,
        Centre = 2,
        MapHere = 3,
        North = 4,
        AirYard = 5,
        Gun = 6,
        Barbers = 7,
        BigSmoke = 8,
        Boatyard = 9,
        BurgerShot = 10,
        Bulldozer = 11,
        CatPink = 12,
        Cesar = 13,
        Chicken = 14,
        Cj = 15,
        Crash1 = 16,
        Diner = 17,
        EmmetGun = 18,
        EnemyAttack = 19,
        Fire = 20,
        Girlfriend = 21,
        Hospital = 22,
        Loco = 23,
        MaddDogg = 24,
        Mafia = 25,
        McsTrap = 26,
        ModGarage = 27,
        OgLoc = 28,
        Pizza = 29,
        Police = 30,
        PropertyGreen = 31,
        PropertyRed = 32,
        Race = 33,
        Ryder = 34,
        SaveHouse = 35,
        School = 36,
        Mystery = 37,
        Sweet = 38,
        Tattoo = 39,
        Truth = 40,
        Waypoint = 41,
        TorenoRanch = 42,
        Triads = 43,
        TriadsCasino = 44,
        Tshirt = 45,
        Woozie = 46,
        Zero = 47,
        DateDisco = 48,
        DateDrink = 49,
        DateFood = 50,
        Truck = 51,
        Cash = 52,
        Flag = 53,
        Gym = 54,
        Impound = 55,
        RunwayLight = 56,
        Runway = 57,
        GangB = 58,
        GangP = 59,
        GangY = 60,
        GangN = 61,
        GangG = 62,
        Spray = 63
    }
}
