using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SlipeServer.Packets.Constants
{
    public class KeyConstants
    {
        public enum Controls
        {
            Fire,
            AimWeapon,
            NextWeapon,
            PreviousWeapon,
            Forwards,
            Backwards,
            Left,
            Right,
            ZoomIn,
            ZoomOut,
            ChangeCamera,
            Jump,
            Sprint,
            LookBehind,
            Crouch,
            Action,
            Walk,
            ConversationYes,
            ConversationNo,
            GroupControlForwards,
            GroupControlBack,
            EnterExit,
            VehicleFire,
            VehicleSecondaryFire,
            VehicleLeft,
            VehicleRight,
            SteerForward,
            SteerBack,
            Accelerate,
            BrakeReverse,
            RadioNext,
            RadioPrevious,
            RadioUserTrackSkip,
            Horn,
            SubMission,
            Handbrake,
            VehicleLookLeft,
            VehicleLookRight,
            VehicleLookBehind,
            VehicleMouseLook,
            SpecialControlLeft,
            SpecialControlRight,
            SpecialControlDown,
            SpecialControlUp
        }

        public enum Keys
        {
            Mouse1,
            Mouse2,
            Mouse3,
            Mouse4,
            Mouse5,
            MouseWheelUp,
            MouseWheelDown,
            ArrowLeft,
            ArrowUp,
            ArrowRight,
            ArrowDown,
            _0,
            _1,
            _2,
            _3,
            _4,
            _5,
            _6,
            _7,
            _8,
            _9,
            A,
            B,
            C,
            D,
            E,
            F,
            G,
            H,
            I,
            J,
            K,
            L,
            M,
            N,
            O,
            P,
            Q,
            R,
            S,
            T,
            U,
            V,
            W,
            X,
            Y,
            Z,
            Num_0,
            Num_1,
            Num_2,
            Num_3,
            Num_4,
            Num_5,
            Num_6,
            Num_7,
            Num_8,
            Num_9,
            NumMul,
            NumAdd,
            NumSep,
            NumSub,
            NumDiv,
            NumDec,
            NumEnter,
            F1,
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            F11,
            F12,
            Escape,
            Backspace,
            Tab,
            LeftAlt,
            RightAlt,
            Enter,
            Space,
            PageUp,
            PageDown,
            End,
            Home,
            Insert,
            Delete,
            LeftShift,
            RightShift,
            LeftCtrl,
            RightCtrl,
            /// <summary> The [ key</summary>
            LeftBracket,
            /// <summary> The ] key</summary>
            RightBracket,
            Pause,
            Capslock,
            Scroll,
            /// <summary> The ; key</summary>
            Semicolon,
            /// <summary> The , key</summary>
            Comma,
            /// <summary> The - key</summary>
            Minus,
            /// <summary> The . key</summary>
            Dot,
            /// <summary> The / key</summary>
            Slash,
            /// <summary> The # key</summary>
            Hash,
            /// <summary> The \ key</summary>
            Backslash,
            /// <summary> The = key</summary>
            Equal
        }

        private static readonly IReadOnlyDictionary<string, Controls> _stringToControl = new Dictionary<string, Controls>
        {
            ["fire"] = Controls.Fire,
            ["aim_weapon"] = Controls.AimWeapon,
            ["next_weapon"] = Controls.NextWeapon,
            ["previous_weapon"] = Controls.PreviousWeapon,
            ["forwards"] = Controls.Forwards,
            ["backwards"] = Controls.Backwards,
            ["left"] = Controls.Left,
            ["right"] = Controls.Right,
            ["zoom_in"] = Controls.ZoomIn,
            ["zoom_out"] = Controls.ZoomOut,
            ["change_camera"] = Controls.ChangeCamera,
            ["jump"] = Controls.Jump,
            ["sprint"] = Controls.Sprint,
            ["look_behind"] = Controls.LookBehind,
            ["crouch"] = Controls.Crouch,
            ["action"] = Controls.Action,
            ["walk"] = Controls.Walk,
            ["conversation_yes"] = Controls.ConversationYes,
            ["conversation_no"] = Controls.ConversationNo,
            ["group_control_forwards"] = Controls.GroupControlForwards,
            ["group_control_back"] = Controls.GroupControlBack,
            ["enter_exit"] = Controls.EnterExit,
            ["vehicle_fire"] = Controls.VehicleFire,
            ["vehicle_secondary_fire"] = Controls.VehicleSecondaryFire,
            ["vehicle_left"] = Controls.VehicleLeft,
            ["vehicle_right"] = Controls.VehicleRight,
            ["steer_forward"] = Controls.SteerForward,
            ["steer_back"] = Controls.SteerBack,
            ["accelerate"] = Controls.Accelerate,
            ["brake_reverse"] = Controls.BrakeReverse,
            ["radio_next"] = Controls.RadioNext,
            ["radio_previous"] = Controls.RadioPrevious,
            ["radio_user_track_skip"] = Controls.RadioUserTrackSkip,
            ["horn"] = Controls.Horn,
            ["sub_mission"] = Controls.SubMission,
            ["handbrake"] = Controls.Handbrake,
            ["vehicle_look_left"] = Controls.VehicleLookLeft,
            ["vehicle_look_right"] = Controls.VehicleLookRight,
            ["vehicle_look_behind"] = Controls.VehicleLookBehind,
            ["vehicle_mouse_look"] = Controls.VehicleMouseLook,
            ["special_control_left"] = Controls.SpecialControlLeft,
            ["special_control_right"] = Controls.SpecialControlRight,
            ["special_control_down"] = Controls.SpecialControlDown,
            ["special_control_up"] = Controls.SpecialControlUp,
        };


        private static readonly IReadOnlyDictionary<Controls, string> _controlToString = new Dictionary<Controls, string>
        {
            [Controls.Fire] = "fire",
            [Controls.AimWeapon] = "aim_weapon",
            [Controls.NextWeapon] = "next_weapon",
            [Controls.PreviousWeapon] = "previous_weapon",
            [Controls.Forwards] = "forwards",
            [Controls.Backwards] = "backwards",
            [Controls.Left] = "left",
            [Controls.Right] = "right",
            [Controls.ZoomIn] = "zoom_in",
            [Controls.ZoomOut] = "zoom_out",
            [Controls.ChangeCamera] = "change_camera",
            [Controls.Jump] = "jump",
            [Controls.Sprint] = "sprint",
            [Controls.LookBehind] = "look_behind",
            [Controls.Crouch] = "crouch",
            [Controls.Action] = "action",
            [Controls.Walk] = "walk",
            [Controls.ConversationYes] = "conversation_yes",
            [Controls.ConversationNo] = "conversation_no",
            [Controls.GroupControlForwards] = "group_control_forwards",
            [Controls.GroupControlBack] = "group_control_back",
            [Controls.EnterExit] = "enter_exit",
            [Controls.VehicleFire] = "vehicle_fire",
            [Controls.VehicleSecondaryFire] = "vehicle_secondary_fire",
            [Controls.VehicleLeft] = "vehicle_left",
            [Controls.VehicleRight] = "vehicle_right",
            [Controls.SteerForward] = "steer_forward",
            [Controls.SteerBack] = "steer_back",
            [Controls.Accelerate] = "accelerate",
            [Controls.BrakeReverse] = "brake_reverse",
            [Controls.RadioNext] = "radio_next",
            [Controls.RadioPrevious] = "radio_previous",
            [Controls.RadioUserTrackSkip] = "radio_user_track_skip",
            [Controls.Horn] = "horn",
            [Controls.SubMission] = "sub_mission",
            [Controls.Handbrake] = "handbrake",
            [Controls.VehicleLookLeft] = "vehicle_look_left",
            [Controls.VehicleLookRight] = "vehicle_look_right",
            [Controls.VehicleLookBehind] = "vehicle_look_behind",
            [Controls.VehicleMouseLook] = "vehicle_mouse_look",
            [Controls.SpecialControlLeft] = "special_control_left",
            [Controls.SpecialControlRight] = "special_control_right",
            [Controls.SpecialControlDown] = "special_control_down",
            [Controls.SpecialControlUp] = "special_control_up",
        };

        private static IReadOnlyDictionary<string, Keys> _stringToKey { get; } = new Dictionary<string, Keys>
        {
            ["mouse1"] = Keys.Mouse1,
            ["mouse2"] = Keys.Mouse2,
            ["mouse3"] = Keys.Mouse3,
            ["mouse4"] = Keys.Mouse4,
            ["mouse5"] = Keys.Mouse5,
            ["mouse_wheel_up"] = Keys.MouseWheelUp,
            ["mouse_wheel_down"] = Keys.MouseWheelDown,
            ["arrow_l"] = Keys.ArrowLeft,
            ["arrow_u"] = Keys.ArrowUp,
            ["arrow_r"] = Keys.ArrowRight,
            ["arrow_d"] = Keys.ArrowDown,
            ["0"] = Keys._0,
            ["1"] = Keys._1,
            ["2"] = Keys._2,
            ["3"] = Keys._3,
            ["4"] = Keys._4,
            ["5"] = Keys._5,
            ["6"] = Keys._6,
            ["7"] = Keys._7,
            ["8"] = Keys._8,
            ["9"] = Keys._9,
            ["a"] = Keys.A,
            ["b"] = Keys.B,
            ["c"] = Keys.C,
            ["d"] = Keys.D,
            ["e"] = Keys.E,
            ["f"] = Keys.F,
            ["g"] = Keys.G,
            ["h"] = Keys.H,
            ["i"] = Keys.I,
            ["j"] = Keys.J,
            ["k"] = Keys.K,
            ["l"] = Keys.L,
            ["m"] = Keys.M,
            ["n"] = Keys.N,
            ["o"] = Keys.O,
            ["p"] = Keys.P,
            ["q"] = Keys.Q,
            ["r"] = Keys.R,
            ["s"] = Keys.S,
            ["t"] = Keys.T,
            ["u"] = Keys.U,
            ["v"] = Keys.V,
            ["w"] = Keys.W,
            ["x"] = Keys.X,
            ["y"] = Keys.Y,
            ["z"] = Keys.Z,
            ["num_0"] = Keys.Num_0,
            ["num_1"] = Keys.Num_1,
            ["num_2"] = Keys.Num_2,
            ["num_3"] = Keys.Num_3,
            ["num_4"] = Keys.Num_4,
            ["num_5"] = Keys.Num_5,
            ["num_6"] = Keys.Num_6,
            ["num_7"] = Keys.Num_7,
            ["num_8"] = Keys.Num_8,
            ["num_9"] = Keys.Num_9,
            ["num_mul"] = Keys.NumMul,
            ["num_add"] = Keys.NumAdd,
            ["num_sep"] = Keys.NumSep,
            ["num_sub"] = Keys.NumSub,
            ["num_div"] = Keys.NumDiv,
            ["num_dec"] = Keys.NumDec,
            ["num_enter"] = Keys.NumEnter,
            ["F1"] = Keys.F1,
            ["F2"] = Keys.F2,
            ["F3"] = Keys.F3,
            ["F4"] = Keys.F4,
            ["F5"] = Keys.F5,
            ["F6"] = Keys.F6,
            ["F7"] = Keys.F7,
            ["F8"] = Keys.F8,
            ["F9"] = Keys.F9,
            ["F10"] = Keys.F10,
            ["F11"] = Keys.F11,
            ["F12"] = Keys.F12,
            ["escape"] = Keys.Escape,
            ["backspace"] = Keys.Backslash,
            ["tab"] = Keys.Tab,
            ["lalt"] = Keys.LeftAlt,
            ["ralt"] = Keys.RightAlt,
            ["enter"] = Keys.Enter,
            ["space"] = Keys.Space,
            ["pgup"] = Keys.PageUp,
            ["pgdn"] = Keys.PageDown,
            ["end"] = Keys.End,
            ["home"] = Keys.Home,
            ["insert"] = Keys.Insert,
            ["delete"] = Keys.Delete,
            ["lshift"] = Keys.LeftShift,
            ["rshift"] = Keys.RightShift,
            ["lctrl"] = Keys.LeftCtrl,
            ["rctrl"] = Keys.RightCtrl,
            ["["] = Keys.LeftBracket,
            ["]"] = Keys.RightBracket,
            ["pause"] = Keys.Pause,
            ["capslock"] = Keys.Capslock,
            ["scroll"] = Keys.Scroll,
            [";"] = Keys.Semicolon,
            [","] = Keys.Comma,
            ["-"] = Keys.Minus,
            ["."] = Keys.Dot,
            ["/"] = Keys.Slash,
            ["#"] = Keys.Hash,
            ["\\"] = Keys.Backslash,
            ["="] = Keys.Equal,
        };

        private static IReadOnlyDictionary<Keys, string> _keyToString { get; } = new Dictionary<Keys, string>
        {
            [Keys.Mouse1] = "mouse1",
            [Keys.Mouse2] = "mouse2",
            [Keys.Mouse3] = "mouse3",
            [Keys.Mouse4] = "mouse4",
            [Keys.Mouse5] = "mouse5",
            [Keys.MouseWheelUp] = "mouse_wheel_up",
            [Keys.MouseWheelDown] = "mouse_wheel_down",
            [Keys.ArrowLeft] = "arrow_l",
            [Keys.ArrowUp] = "arrow_u",
            [Keys.ArrowRight] = "arrow_r",
            [Keys.ArrowDown] = "arrow_d",
            [Keys._0] = "0",
            [Keys._1] = "1",
            [Keys._2] = "2",
            [Keys._3] = "3",
            [Keys._4] = "4",
            [Keys._5] = "5",
            [Keys._6] = "6",
            [Keys._7] = "7",
            [Keys._8] = "8",
            [Keys._9] = "9",
            [Keys.A] = "a",
            [Keys.B] = "b",
            [Keys.C] = "c",
            [Keys.D] = "d",
            [Keys.E] = "e",
            [Keys.F] = "f",
            [Keys.G] = "g",
            [Keys.H] = "h",
            [Keys.I] = "i",
            [Keys.J] = "j",
            [Keys.K] = "k",
            [Keys.L] = "l",
            [Keys.M] = "m",
            [Keys.N] = "n",
            [Keys.O] = "o",
            [Keys.P] = "p",
            [Keys.Q] = "q",
            [Keys.R] = "r",
            [Keys.S] = "s",
            [Keys.T] = "t",
            [Keys.U] = "u",
            [Keys.V] = "v",
            [Keys.W] = "w",
            [Keys.X] = "x",
            [Keys.Y] = "y",
            [Keys.Z] = "z",
            [Keys.Num_0] = "num_0",
            [Keys.Num_1] = "num_1",
            [Keys.Num_2] = "num_2",
            [Keys.Num_3] = "num_3",
            [Keys.Num_4] = "num_4",
            [Keys.Num_5] = "num_5",
            [Keys.Num_6] = "num_6",
            [Keys.Num_7] = "num_7",
            [Keys.Num_8] = "num_8",
            [Keys.Num_9] = "num_9",
            [Keys.NumMul] = "num_mul",
            [Keys.NumAdd] = "num_add",
            [Keys.NumSep] = "num_sep",
            [Keys.NumSub] = "num_sub",
            [Keys.NumDiv] = "num_div",
            [Keys.NumDec] = "num_dec",
            [Keys.NumEnter] = "num_enter",
            [Keys.F1] = "F1",
            [Keys.F2] = "F2",
            [Keys.F3] = "F3",
            [Keys.F4] = "F4",
            [Keys.F5] = "F5",
            [Keys.F6] = "F6",
            [Keys.F7] = "F7",
            [Keys.F8] = "F8",
            [Keys.F9] = "F9",
            [Keys.F10] = "F10",
            [Keys.F11] = "F11",
            [Keys.F12] = "F12",
            [Keys.Escape] = "escape",
            [Keys.Backslash] = "backspace",
            [Keys.Tab] = "tab",
            [Keys.LeftAlt] = "lalt",
            [Keys.RightAlt] = "ralt",
            [Keys.Enter] = "enter",
            [Keys.Space] = "space",
            [Keys.PageUp] = "pgup",
            [Keys.PageDown] = "pgdn",
            [Keys.End] = "end",
            [Keys.Home] = "home",
            [Keys.Insert] = "insert",
            [Keys.Delete] = "delete",
            [Keys.LeftShift] = "lshift",
            [Keys.RightShift] = "rshift",
            [Keys.LeftCtrl] = "lctrl",
            [Keys.RightCtrl] = "rctrl",
            [Keys.LeftBracket] = "[",
            [Keys.RightBracket] = "]",
            [Keys.Pause] = "pause",
            [Keys.Capslock] = "capslock",
            [Keys.Scroll] = "scroll",
            [Keys.Semicolon] = ";",
            [Keys.Comma] = ",",
            [Keys.Minus] = "-",
            [Keys.Dot] = ".",
            [Keys.Slash] = "/",
            [Keys.Hash] = "#",
            [Keys.Backslash] = "\\",
            [Keys.Equal] = "=",
        };

        public static string ControlToString(Controls control) => _controlToString[control];
        public static Controls StringToControl(string control) => _stringToControl[control];
        public static string KeyToString(Keys key) => _keyToString[key];
        public static Keys StringToKey(string key) => _stringToKey[key];

        public static bool IsValid(string controlOrKey) => _stringToControl.ContainsKey(controlOrKey) || _stringToKey.ContainsKey(controlOrKey);

    }
}
