namespace SlipeServer.Server.Enums;

public enum GlitchType
{
    GLITCH_QUICKRELOAD,
    GLITCH_FASTFIRE,
    GLITCH_FASTMOVE,
    GLITCH_CROUCHBUG,
    GLITCH_CLOSEDAMAGE,
    GLITCH_HITANIM,
    GLITCH_FASTSPRINT,
    GLITCH_BADDRIVEBYHITBOX,
    GLITCH_QUICKSTAND,
    GLITCH_KICKOUTOFVEHICLE_ONMODELREPLACE,
    GLITCH_VEHICLE_RAPID_STOP,
};
