namespace SlipeServer.Server.Enums;

public enum VehicleHandlingProperty : byte
{
    Mass = 1,
    TurnMass,
    DragCoefficient,
    CenterOfMass,
    PercentSubmerged,
    TractionMultiplier,
    DriveType,
    EngineType,
    NumberOfGears,
    EngineAcceleration,
    EngineInertia,
    MaxVelocity,
    BrakeDeceleration,
    BrakeBias,
    Abs,
    SteeringLock,
    TractionLoss,
    TractionBias,
    SuspensionForceLevel,
    SuspensionDamping,
    SuspensionHighSpeedDaming,
    SuspensionUpperLimit,
    SuspensionLowerLimit,
    SuspensionFrontRearBias,
    SuspensionAntiDiveMultiplier,
    CollisionDamageMultiplier,
    SeatOffsetDistance,
    Monetary,
    HandlingFlags,
    ModelFlags,
    Headlight,
    Taillight,
    AnimGroup,
}
