using SlipeServer.Packets.Definitions.Entities.Structs;
using SlipeServer.Server.Enums;
using System.Collections.Generic;

namespace SlipeServer.Server.Constants;

public class ClothingConstants
{
    public static Dictionary<ClothingType, byte> Defaults { get; } = new()
    {
        [ClothingType.Shirt] = 1,
        [ClothingType.Head] = 0,
        [ClothingType.Trousers] = 7,
        [ClothingType.Shoes] = 6,
    };

    public static Dictionary<ClothingType, PedClothing[]> ClothesTextureModel { get; } = new()
    {
        [ClothingType.Shirt] = new PedClothing[] {
                new PedClothing("player_torso", "torso", (byte)ClothingType.Shirt),
                new PedClothing("vestblack", "vest", (byte)ClothingType.Shirt),
                new PedClothing("vest", "vest", (byte)ClothingType.Shirt),
                new PedClothing("tshirt2horiz", "tshirt2", (byte)ClothingType.Shirt),
                new PedClothing("tshirtwhite", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtilovels", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtblunts", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("shirtbplaid", "shirtb", (byte)ClothingType.Shirt),
                new PedClothing("shirtbcheck", "shirtb", (byte)ClothingType.Shirt),
                new PedClothing("field", "field", (byte)ClothingType.Shirt),
                new PedClothing("tshirterisyell", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirterisorn", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("trackytop2eris", "trackytop1", (byte)ClothingType.Shirt),
                new PedClothing("bbjackrim", "bbjack", (byte)ClothingType.Shirt),
                new PedClothing("bballjackrstar", "bbjack", (byte)ClothingType.Shirt),
                new PedClothing("baskballdrib", "baskball", (byte)ClothingType.Shirt),
                new PedClothing("baskballrim", "baskball", (byte)ClothingType.Shirt),
                new PedClothing("sixtyniners", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("bandits", "baseball", (byte)ClothingType.Shirt),
                new PedClothing("tshirtprored", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtproblk", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("trackytop1pro", "trackytop1", (byte)ClothingType.Shirt),
                new PedClothing("hockeytop", "sweat", (byte)ClothingType.Shirt),
                new PedClothing("bbjersey", "sleevt", (byte)ClothingType.Shirt),
                new PedClothing("shellsuit", "trackytop1", (byte)ClothingType.Shirt),
                new PedClothing("tshirtheatwht", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtbobomonk", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtbobored", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtbase5", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtsuburb", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("hoodyamerc", "hoodya", (byte)ClothingType.Shirt),
                new PedClothing("hoodyabase5", "hoodya", (byte)ClothingType.Shirt),
                new PedClothing("hoodyarockstar", "hoodya", (byte)ClothingType.Shirt),
                new PedClothing("wcoatblue", "wcoat", (byte)ClothingType.Shirt),
                new PedClothing("coach", "coach", (byte)ClothingType.Shirt),
                new PedClothing("coachsemi", "coach", (byte)ClothingType.Shirt),
                new PedClothing("sweatrstar", "sweat", (byte)ClothingType.Shirt),
                new PedClothing("hoodyAblue", "hoodyA", (byte)ClothingType.Shirt),
                new PedClothing("hoodyAblack", "hoodyA", (byte)ClothingType.Shirt),
                new PedClothing("hoodyAgreen", "hoodyA", (byte)ClothingType.Shirt),
                new PedClothing("sleevtbrown", "sleevt", (byte)ClothingType.Shirt),
                new PedClothing("shirtablue", "shirta", (byte)ClothingType.Shirt),
                new PedClothing("shirtayellow", "shirta", (byte)ClothingType.Shirt),
                new PedClothing("shirtagrey", "shirta", (byte)ClothingType.Shirt),
                new PedClothing("shirtbgang", "shirtb", (byte)ClothingType.Shirt),
                new PedClothing("tshirtzipcrm", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtzipgry", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("denimfade", "denim", (byte)ClothingType.Shirt),
                new PedClothing("bowling", "hawaii", (byte)ClothingType.Shirt),
                new PedClothing("hoodjackbeige", "hoodjack", (byte)ClothingType.Shirt),
                new PedClothing("baskballloc", "baskball", (byte)ClothingType.Shirt),
                new PedClothing("tshirtlocgrey", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtmaddgrey", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("tshirtmaddgrn", "tshirt", (byte)ClothingType.Shirt),
                new PedClothing("suit1grey", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("suit1blk", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("leather", "leather", (byte)ClothingType.Shirt),
                new PedClothing("painter", "painter", (byte)ClothingType.Shirt),
                new PedClothing("hawaiiwht", "hawaii", (byte)ClothingType.Shirt),
                new PedClothing("hawaiired", "hawaii", (byte)ClothingType.Shirt),
                new PedClothing("sportjack", "trackytop1", (byte)ClothingType.Shirt),
                new PedClothing("suit1red", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("suit1blue", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("suit1yellow", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("suit2grn", "suit2", (byte)ClothingType.Shirt),
                new PedClothing("tuxedo", "suit2", (byte)ClothingType.Shirt),
                new PedClothing("suit1gang", "suit1", (byte)ClothingType.Shirt),
                new PedClothing("letter", "sleevt", (byte)ClothingType.Shirt),
            },

        [ClothingType.Head] = new PedClothing[] {
                new PedClothing("player_face", "head", (byte)ClothingType.Head),
                new PedClothing("hairblond", "head", (byte)ClothingType.Head),
                new PedClothing("hairred", "head", (byte)ClothingType.Head),
                new PedClothing("hairblue", "head", (byte)ClothingType.Head),
                new PedClothing("hairgreen", "head", (byte)ClothingType.Head),
                new PedClothing("hairpink", "head", (byte)ClothingType.Head),
                new PedClothing("bald", "head", (byte)ClothingType.Head),
                new PedClothing("baldbeard", "head", (byte)ClothingType.Head),
                new PedClothing("baldtash", "head", (byte)ClothingType.Head),
                new PedClothing("baldgoatee", "head", (byte)ClothingType.Head),
                new PedClothing("highfade", "head", (byte)ClothingType.Head),
                new PedClothing("highafro", "highafro", (byte)ClothingType.Head),
                new PedClothing("wedge", "wedge", (byte)ClothingType.Head),
                new PedClothing("slope", "slope", (byte)ClothingType.Head),
                new PedClothing("jhericurl", "jhericurl", (byte)ClothingType.Head),
                new PedClothing("cornrows", "cornrows", (byte)ClothingType.Head),
                new PedClothing("cornrowsb", "cornrows", (byte)ClothingType.Head),
                new PedClothing("tramline", "tramline", (byte)ClothingType.Head),
                new PedClothing("groovecut", "groovecut", (byte)ClothingType.Head),
                new PedClothing("mohawk", "mohawk", (byte)ClothingType.Head),
                new PedClothing("mohawkblond", "mohawkblond", (byte)ClothingType.Head),
                new PedClothing("mohawkpink", "mohawk", (byte)ClothingType.Head),
                new PedClothing("mohawkbeard", "mohawk", (byte)ClothingType.Head),
                new PedClothing("afro", "afro", (byte)ClothingType.Head),
                new PedClothing("afrotash", "afro", (byte)ClothingType.Head),
                new PedClothing("afrobeard", "afro", (byte)ClothingType.Head),
                new PedClothing("afroblond", "afro", (byte)ClothingType.Head),
                new PedClothing("flattop", "flattop", (byte)ClothingType.Head),
                new PedClothing("elvishair", "elvishair", (byte)ClothingType.Head),
                new PedClothing("beard", "beard", (byte)ClothingType.Head),
                new PedClothing("tash", "head", (byte)ClothingType.Head),
                new PedClothing("goatee", "head", (byte)ClothingType.Head),
                new PedClothing("afrogoatee", "afro", (byte)ClothingType.Head),
            },
        [ClothingType.Trousers] = new PedClothing[] {
                new PedClothing("player_legs", "legs", (byte)ClothingType.Trousers),
                new PedClothing("worktrcamogrn", "worktr", (byte)ClothingType.Trousers),
                new PedClothing("worktrcamogry", "worktr", (byte)ClothingType.Trousers),
                new PedClothing("worktrgrey", "worktr", (byte)ClothingType.Trousers),
                new PedClothing("worktrkhaki", "worktr", (byte)ClothingType.Trousers),
                new PedClothing("tracktr", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("tracktreris", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("jeansdenim", "jeans", (byte)ClothingType.Trousers),
                new PedClothing("legsblack", "legs", (byte)ClothingType.Trousers),
                new PedClothing("legsheart", "legs", (byte)ClothingType.Trousers),
                new PedClothing("biegetr", "chinosb", (byte)ClothingType.Trousers),
                new PedClothing("tracktrpro", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("tracktrwhstr", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("tracktrblue", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("tracktrgang", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("bbshortwht", "bbshortwht", (byte)ClothingType.Trousers),
                new PedClothing("boxshort", "boxingshort", (byte)ClothingType.Trousers),
                new PedClothing("bbshortred", "boxingshort", (byte)ClothingType.Trousers),
                new PedClothing("shellsuittr", "tracktr", (byte)ClothingType.Trousers),
                new PedClothing("shortsgrey", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("shortskhaki", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("chongergrey", "chonger", (byte)ClothingType.Trousers),
                new PedClothing("chongergang", "chonger", (byte)ClothingType.Trousers),
                new PedClothing("chongerred", "chonger", (byte)ClothingType.Trousers),
                new PedClothing("chongerblue", "chonger", (byte)ClothingType.Trousers),
                new PedClothing("shortsgang", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("denimsgang", "jeans", (byte)ClothingType.Trousers),
                new PedClothing("denimsred", "jeans", (byte)ClothingType.Trousers),
                new PedClothing("chinosbiege", "chinosb", (byte)ClothingType.Trousers),
                new PedClothing("chinoskhaki", "chinosb", (byte)ClothingType.Trousers),
                new PedClothing("cutoffchinos", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("cutoffchinosblue", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("chinosblack", "chinosb", (byte)ClothingType.Trousers),
                new PedClothing("chinosblue", "chinosb", (byte)ClothingType.Trousers),
                new PedClothing("leathertr", "leathertr", (byte)ClothingType.Trousers),
                new PedClothing("leathertrchaps", "leathertr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trgrey", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trblk", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("cutoffdenims", "shorts", (byte)ClothingType.Trousers),
                new PedClothing("suit1trred", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trblue", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1tryellow", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trgreen", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trblk2", "suit1tr", (byte)ClothingType.Trousers),
                new PedClothing("suit1trgang", "suit1tr", (byte)ClothingType.Trousers),
            },
        [ClothingType.Shoes] = new PedClothing[] {
                new PedClothing("foot", "feet", (byte)ClothingType.Shoes),
                new PedClothing("cowboyboot2", "biker", (byte)ClothingType.Shoes),
                new PedClothing("bask2semi", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("bask1eris", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("sneakerbincgang", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerbincblu", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerbincblk", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sandal", "flipflop", (byte)ClothingType.Shoes),
                new PedClothing("sandalsock", "flipflop", (byte)ClothingType.Shoes),
                new PedClothing("flipflop", "flipflop", (byte)ClothingType.Shoes),
                new PedClothing("hitop", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("convproblk", "conv", (byte)ClothingType.Shoes),
                new PedClothing("convproblu", "conv", (byte)ClothingType.Shoes),
                new PedClothing("convprogrn", "conv", (byte)ClothingType.Shoes),
                new PedClothing("sneakerprored", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerproblu", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerprowht", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("bask1prowht", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("bask1problk", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("boxingshoe", "biker", (byte)ClothingType.Shoes),
                new PedClothing("convheatblk", "conv", (byte)ClothingType.Shoes),
                new PedClothing("convheatred", "conv", (byte)ClothingType.Shoes),
                new PedClothing("convheatorn", "conv", (byte)ClothingType.Shoes),
                new PedClothing("sneakerheatwht", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerheatgry", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("sneakerheatblk", "sneaker", (byte)ClothingType.Shoes),
                new PedClothing("bask2heatwht", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("bask2heatband", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("timbergrey", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("timberred", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("timberfawn", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("timberhike", "bask1", (byte)ClothingType.Shoes),
                new PedClothing("cowboyboot", "biker", (byte)ClothingType.Shoes),
                new PedClothing("biker", "biker", (byte)ClothingType.Shoes),
                new PedClothing("snakeskin", "biker", (byte)ClothingType.Shoes),
                new PedClothing("shoedressblk", "shoe", (byte)ClothingType.Shoes),
                new PedClothing("shoedressbrn", "shoe", (byte)ClothingType.Shoes),
                new PedClothing("shoespatz", "shoe", (byte)ClothingType.Shoes),
            },
        [ClothingType.TattoosLeftUpperArm] = new PedClothing[] {
                new PedClothing("4weed", "4WEED", (byte)ClothingType.TattoosLeftUpperArm),
                new PedClothing("4rip", "4RIP", (byte)ClothingType.TattoosLeftUpperArm),
                new PedClothing("4spider", "4SPIDER", (byte)ClothingType.TattoosLeftUpperArm),
            },
        [ClothingType.TattoosLeftLowerArm] = new PedClothing[] {
                new PedClothing("5gun", "5GUN", (byte)ClothingType.TattoosLeftLowerArm),
                new PedClothing("5cross", "5CROSS", (byte)ClothingType.TattoosLeftLowerArm),
                new PedClothing("5cross2", "5CROSS2", (byte)ClothingType.TattoosLeftLowerArm),
                new PedClothing("5cross3", "5CROSS3", (byte)ClothingType.TattoosLeftLowerArm),
            },
        [ClothingType.TattoosRightUpperArm] = new PedClothing[] {
                new PedClothing("6aztec", "6AZTEC", (byte)ClothingType.TattoosRightUpperArm),
                new PedClothing("6crown", "6CROWN", (byte)ClothingType.TattoosRightUpperArm),
                new PedClothing("6clown", "6CLOWN", (byte)ClothingType.TattoosRightUpperArm),
                new PedClothing("6africa", "6AFRICA", (byte)ClothingType.TattoosRightUpperArm),
            },
        [ClothingType.TattoosRightLowerArm] = new PedClothing[] {
                new PedClothing("7cross", "7CROSS", (byte)ClothingType.TattoosRightLowerArm),
                new PedClothing("7cross2", "7CROSS2", (byte)ClothingType.TattoosRightLowerArm),
                new PedClothing("7cross3", "7CROSS3", (byte)ClothingType.TattoosRightLowerArm),
                new PedClothing("7mary", "7MARY", (byte)ClothingType.TattoosRightLowerArm),
            },
        [ClothingType.TattoosBack] = new PedClothing[] {
                new PedClothing("8sa", "8SA", (byte)ClothingType.TattoosBack),
                new PedClothing("8sa2", "8SA2", (byte)ClothingType.TattoosBack),
                new PedClothing("8sa3", "8SA3", (byte)ClothingType.TattoosBack),
                new PedClothing("8westside", "8WESTSD", (byte)ClothingType.TattoosBack),
                new PedClothing("8santos", "8SANTOS", (byte)ClothingType.TattoosBack),
                new PedClothing("8poker", "8POKER", (byte)ClothingType.TattoosBack),
                new PedClothing("8gun", "8GUN", (byte)ClothingType.TattoosBack),
            },
        [ClothingType.TattoosLeftChest] = new PedClothing[] {
                new PedClothing("9crown", "9CROWN", (byte)ClothingType.TattoosLeftChest),
                new PedClothing("9gun", "9GUN", (byte)ClothingType.TattoosLeftChest),
                new PedClothing("9gun2", "9GUN2", (byte)ClothingType.TattoosLeftChest),
                new PedClothing("9homeboy", "9HOMBY", (byte)ClothingType.TattoosLeftChest),
                new PedClothing("9bullet", "9BULLT", (byte)ClothingType.TattoosLeftChest),
                new PedClothing("9rasta", "9RASTA", (byte)ClothingType.TattoosLeftChest),
            },
        [ClothingType.TattoosRightChest] = new PedClothing[] {
                new PedClothing("10ls", "10LS", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10ls2", "10LS2", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10ls3", "10LS3", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10ls4", "10LS4", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10ls5", "10ls5", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10og", "10OG", (byte)ClothingType.TattoosRightChest),
                new PedClothing("10weed", "10WEED", (byte)ClothingType.TattoosRightChest),
            },
        [ClothingType.TattoosStomach] = new PedClothing[] {
                new PedClothing("11grove", "11GROVE", (byte)ClothingType.TattoosStomach),
                new PedClothing("11grove2", "11GROV2", (byte)ClothingType.TattoosStomach),
                new PedClothing("11grove3", "11GROV3", (byte)ClothingType.TattoosStomach),
                new PedClothing("11dice", "11DICE", (byte)ClothingType.TattoosStomach),
                new PedClothing("11dice2", "11DICE2", (byte)ClothingType.TattoosStomach),
                new PedClothing("11jail", "11JAIL", (byte)ClothingType.TattoosStomach),
                new PedClothing("11godsgift", "11GGIFT", (byte)ClothingType.TattoosStomach),
            },
        [ClothingType.TattoosLowerBack] = new PedClothing[] {
                new PedClothing("12angels", "12ANGEL", (byte)ClothingType.TattoosLowerBack),
                new PedClothing("12mayabird", "12MAYBR", (byte)ClothingType.TattoosLowerBack),
                new PedClothing("12dagger", "12DAGER", (byte)ClothingType.TattoosLowerBack),
                new PedClothing("12bandit", "12BNDIT", (byte)ClothingType.TattoosLowerBack),
                new PedClothing("12cross7", "12CROSS", (byte)ClothingType.TattoosLowerBack),
                new PedClothing("12mayafce", "12MYFAC", (byte)ClothingType.TattoosLowerBack),
            },
        [ClothingType.Necklace] = new PedClothing[] {
                new PedClothing("dogtag", "neck", (byte)ClothingType.Necklace),
                new PedClothing("neckafrica", "neck", (byte)ClothingType.Necklace),
                new PedClothing("stopwatch", "neck", (byte)ClothingType.Necklace),
                new PedClothing("necksaints", "neck", (byte)ClothingType.Necklace),
                new PedClothing("neckhash", "neck", (byte)ClothingType.Necklace),
                new PedClothing("necksilver", "neck2", (byte)ClothingType.Necklace),
                new PedClothing("neckgold", "neck2", (byte)ClothingType.Necklace),
                new PedClothing("neckropes", "neck2", (byte)ClothingType.Necklace),
                new PedClothing("neckropeg", "neck2", (byte)ClothingType.Necklace),
                new PedClothing("neckls", "neck", (byte)ClothingType.Necklace),
                new PedClothing("neckdollar", "neck2", (byte)ClothingType.Necklace),
                new PedClothing("neckcross", "neck2", (byte)ClothingType.Necklace),
            },
        [ClothingType.Watches] = new PedClothing[] {
                new PedClothing("watchpink", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchyellow", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchpro", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchpro2", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchsub1", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchsub2", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchzip1", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchzip2", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchgno", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchgno2", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchcro", "watch", (byte)ClothingType.Watches),
                new PedClothing("watchcro2", "watch", (byte)ClothingType.Watches),
            },
        [ClothingType.Glasses] = new PedClothing[] {
                new PedClothing("groucho", "grouchos", (byte)ClothingType.Glasses),
                new PedClothing("zorro", "zorromask", (byte)ClothingType.Glasses),
                new PedClothing("eyepatch", "eyepatch", (byte)ClothingType.Glasses),
                new PedClothing("glasses01", "glasses01", (byte)ClothingType.Glasses),
                new PedClothing("glasses04", "glasses04", (byte)ClothingType.Glasses),
                new PedClothing("bandred3", "bandmask", (byte)ClothingType.Glasses),
                new PedClothing("bandblue3", "bandmask", (byte)ClothingType.Glasses),
                new PedClothing("bandgang3", "bandmask", (byte)ClothingType.Glasses),
                new PedClothing("bandblack3", "bandmask", (byte)ClothingType.Glasses),
                new PedClothing("glasses01dark", "glasses01", (byte)ClothingType.Glasses),
                new PedClothing("glasses04dark", "glasses04", (byte)ClothingType.Glasses),
                new PedClothing("glasses03", "glasses03", (byte)ClothingType.Glasses),
                new PedClothing("glasses03red", "glasses03", (byte)ClothingType.Glasses),
                new PedClothing("glasses03blue", "glasses03", (byte)ClothingType.Glasses),
                new PedClothing("glasses03dark", "glasses03", (byte)ClothingType.Glasses),
                new PedClothing("glasses05dark", "glasses03", (byte)ClothingType.Glasses),
                new PedClothing("glasses05", "glasses03", (byte)ClothingType.Glasses),
            },
        [ClothingType.Hats] = new PedClothing[] {
                new PedClothing("bandred", "bandana", (byte)ClothingType.Hats),
                new PedClothing("bandblue", "bandana", (byte)ClothingType.Hats),
                new PedClothing("bandgang", "bandana", (byte)ClothingType.Hats),
                new PedClothing("bandblack", "bandana", (byte)ClothingType.Hats),
                new PedClothing("bandred2", "bandknots", (byte)ClothingType.Hats),
                new PedClothing("bandblue2", "bandknots", (byte)ClothingType.Hats),
                new PedClothing("bandblack2", "bandknots", (byte)ClothingType.Hats),
                new PedClothing("bandgang2", "bandknots", (byte)ClothingType.Hats),
                new PedClothing("capknitgrn", "capknit", (byte)ClothingType.Hats),
                new PedClothing("captruck", "captruck", (byte)ClothingType.Hats),
                new PedClothing("cowboy", "cowboy", (byte)ClothingType.Hats),
                new PedClothing("hattiger", "cowboy", (byte)ClothingType.Hats),
                new PedClothing("helmet", "helmet", (byte)ClothingType.Hats),
                new PedClothing("moto", "moto", (byte)ClothingType.Hats),
                new PedClothing("boxingcap", "boxingcap", (byte)ClothingType.Hats),
                new PedClothing("hockey", "hockeymask", (byte)ClothingType.Hats),
                new PedClothing("capgang", "cap", (byte)ClothingType.Hats),
                new PedClothing("capgangback", "capback", (byte)ClothingType.Hats),
                new PedClothing("capgangside", "capside", (byte)ClothingType.Hats),
                new PedClothing("capgangover", "capovereye", (byte)ClothingType.Hats),
                new PedClothing("capgangup", "caprimup", (byte)ClothingType.Hats),
                new PedClothing("bikerhelmet", "bikerhelmet", (byte)ClothingType.Hats),
                new PedClothing("capred", "cap", (byte)ClothingType.Hats),
                new PedClothing("capredback", "capback", (byte)ClothingType.Hats),
                new PedClothing("capredside", "capside", (byte)ClothingType.Hats),
                new PedClothing("capredover", "capovereye", (byte)ClothingType.Hats),
                new PedClothing("capredup", "caprimup", (byte)ClothingType.Hats),
                new PedClothing("capblue", "cap", (byte)ClothingType.Hats),
                new PedClothing("capblueback", "capback", (byte)ClothingType.Hats),
                new PedClothing("capblueside", "capside", (byte)ClothingType.Hats),
                new PedClothing("capblueover", "capovereye", (byte)ClothingType.Hats),
                new PedClothing("capblueup", "caprimup", (byte)ClothingType.Hats),
                new PedClothing("skullyblk", "skullycap", (byte)ClothingType.Hats),
                new PedClothing("skullygrn", "skullycap", (byte)ClothingType.Hats),
                new PedClothing("hatmancblk", "hatmanc", (byte)ClothingType.Hats),
                new PedClothing("hatmancplaid", "hatmanc", (byte)ClothingType.Hats),
                new PedClothing("capzip", "cap", (byte)ClothingType.Hats),
                new PedClothing("capzipback", "capback", (byte)ClothingType.Hats),
                new PedClothing("capzipside", "capside", (byte)ClothingType.Hats),
                new PedClothing("capzipover", "capovereye", (byte)ClothingType.Hats),
                new PedClothing("capzipup", "caprimup", (byte)ClothingType.Hats),
                new PedClothing("beretred", "beret", (byte)ClothingType.Hats),
                new PedClothing("beretblk", "beret", (byte)ClothingType.Hats),
                new PedClothing("capblk", "cap", (byte)ClothingType.Hats),
                new PedClothing("capblkback", "capback", (byte)ClothingType.Hats),
                new PedClothing("capblkside", "capside", (byte)ClothingType.Hats),
                new PedClothing("capblkover", "capovereye", (byte)ClothingType.Hats),
                new PedClothing("capblkup", "caprimup", (byte)ClothingType.Hats),
                new PedClothing("trilbydrk", "trilby", (byte)ClothingType.Hats),
                new PedClothing("trilbylght", "trilby", (byte)ClothingType.Hats),
                new PedClothing("bowler", "bowler", (byte)ClothingType.Hats),
                new PedClothing("bowlerred", "bowler", (byte)ClothingType.Hats),
                new PedClothing("bowlerblue", "bowler", (byte)ClothingType.Hats),
                new PedClothing("bowleryellow", "bowler", (byte)ClothingType.Hats),
                new PedClothing("boater", "boater", (byte)ClothingType.Hats),
                new PedClothing("bowlergang", "bowler", (byte)ClothingType.Hats),
                new PedClothing("boaterblk", "boater", (byte)ClothingType.Hats),
            },
        [ClothingType.Extra] = new PedClothing[] {
                new PedClothing("gimpleg", "gimpleg", (byte)ClothingType.Extra),
                new PedClothing("valet", "valet", (byte)ClothingType.Extra),
                new PedClothing("countrytr", "countrytr", (byte)ClothingType.Extra),
                new PedClothing("valet", "valet", (byte)ClothingType.Extra),
                new PedClothing("policetr", "policetr", (byte)ClothingType.Extra),
                new PedClothing("balaclava", "balaclava", (byte)ClothingType.Extra),
                new PedClothing("pimptr", "pimptr", (byte)ClothingType.Extra),
                new PedClothing("garageleg", "garagetr", (byte)ClothingType.Extra),
                new PedClothing("medictr", "medictr", (byte)ClothingType.Extra),
            },
    };

    public static int ShirtsCount => ClothesTextureModel[ClothingType.Shirt].Length;
    public static int HeadsCount => ClothesTextureModel[ClothingType.Head].Length;
    public static int TrousersCount => ClothesTextureModel[ClothingType.Trousers].Length;
    public static int ShoesCount => ClothesTextureModel[ClothingType.Shoes].Length;
    public static int TattoosLeftUpperArmCount => ClothesTextureModel[ClothingType.TattoosLeftUpperArm].Length;
    public static int TattoosLeftLowerArmCount => ClothesTextureModel[ClothingType.TattoosLeftLowerArm].Length;
    public static int TattoosRightUpperArmCount => ClothesTextureModel[ClothingType.TattoosRightUpperArm].Length;
    public static int TattoosRightLowerArmCount => ClothesTextureModel[ClothingType.TattoosRightLowerArm].Length;
    public static int TattoosBackCount => ClothesTextureModel[ClothingType.TattoosBack].Length;
    public static int TattoosLeftChestCount => ClothesTextureModel[ClothingType.TattoosLeftChest].Length;
    public static int TattoosRightChestCount => ClothesTextureModel[ClothingType.TattoosRightChest].Length;
    public static int TattoosStomachCount => ClothesTextureModel[ClothingType.TattoosStomach].Length;
    public static int TattoosLowerBackCount => ClothesTextureModel[ClothingType.TattoosLowerBack].Length;
    public static int NecklaceCount => ClothesTextureModel[ClothingType.Necklace].Length;
    public static int WatchesCount => ClothesTextureModel[ClothingType.Watches].Length;
    public static int GlassesCount => ClothesTextureModel[ClothingType.Glasses].Length;
    public static int HatsCount => ClothesTextureModel[ClothingType.Hats].Length;
    public static int ExtraCount => ClothesTextureModel[ClothingType.Extra].Length;
}
