using SlipeServer.Server.Elements;
using System.Collections.Generic;

namespace SlipeServer.Server.Constants;

public class VehicleConstants
{
    public static HashSet<VehicleModel> TrailerModels { get; } = new()
    {
        VehicleModel.Trailer1,
        VehicleModel.Trailer2,
        VehicleModel.TrailerTankerCommando,
        VehicleModel.Trailer3,
        VehicleModel.BaggageTrailerCovered,
        VehicleModel.BaggageTrailerUncovered,
        VehicleModel.TrailerStairs,
        VehicleModel.FarmTrailer,
        VehicleModel.FarmTrailerTwo
    };

    public static HashSet<VehicleModel> WaterEntryVehicles { get; } = new()
    {
        VehicleModel.Leviathan,
        VehicleModel.Seasparrow,
        VehicleModel.Skimmer,
        VehicleModel.Vortex
    };

    public static HashSet<VehicleModel> VehiclesWithoutDoors { get; } = new()
    {
        VehicleModel.BFInjection,
        VehicleModel.RCBandit,
        VehicleModel.Caddy,
        VehicleModel.RCRaider,
        VehicleModel.Baggage,
        VehicleModel.Dozer,
        VehicleModel.Forklift,
        VehicleModel.Tractor,
        VehicleModel.RCTiger,
        VehicleModel.Bandito,
        VehicleModel.Kart,
        VehicleModel.Mower,
        VehicleModel.RCCam,
        VehicleModel.RCGoblin,
        VehicleModel.BloodringBanger,

        VehicleModel.Coastguard,
        VehicleModel.Dinghy,
        VehicleModel.Jetmax,
        VehicleModel.Launch,
        VehicleModel.Marquis,
        VehicleModel.Predator,
        VehicleModel.Reefer,
        VehicleModel.Speeder,
        VehicleModel.Squalo,
        VehicleModel.Tropic,

        VehicleModel.BF400,
        VehicleModel.Bike,
        VehicleModel.BMX,
        VehicleModel.Faggio,
        VehicleModel.FCR900,
        VehicleModel.Freeway,
        VehicleModel.MountainBike,
        VehicleModel.NRG500,
        VehicleModel.PCJ600,
        VehicleModel.Pizzaboy,
        VehicleModel.Sanchez,
        VehicleModel.Wayfarer,
        VehicleModel.HPV1000,

        VehicleModel.BoxFreight,
        VehicleModel.Streak,
        VehicleModel.StreakTrainTrailer,
        VehicleModel.FreightTrainFlatbed,
        VehicleModel.Freight,
        VehicleModel.Tram,
    };



    public static Dictionary<VehicleModel, byte> DoorsPerVehicle { get; } = new()
    {
        [VehicleModel.Landstalker] = 4,
        [VehicleModel.Bravura] = 4,
        [VehicleModel.Buffalo] = 4,
        [VehicleModel.Linerunner] = 4,
        [VehicleModel.Perennial] = 4,
        [VehicleModel.Sentinel] = 4,
        [VehicleModel.Dumper] = 1,
        [VehicleModel.FireTruck] = 2,
        [VehicleModel.Trashmaster] = 2,
        [VehicleModel.Stretch] = 4,
        [VehicleModel.Manana] = 2,
        [VehicleModel.Infernus] = 2,
        [VehicleModel.Voodoo] = 4,
        [VehicleModel.Pony] = 4,
        [VehicleModel.Mule] = 4,
        [VehicleModel.Cheetah] = 2,
        [VehicleModel.Ambulance] = 4,
        [VehicleModel.Leviathan] = 2,
        [VehicleModel.Moonbeam] = 4,
        [VehicleModel.Esperanto] = 4,
        [VehicleModel.Taxi] = 4,
        [VehicleModel.Washington] = 4,
        [VehicleModel.Bobcat] = 2,
        [VehicleModel.MrWhoopee] = 2,
        [VehicleModel.BFInjection] = 2,
        [VehicleModel.Hunter] = 1,
        [VehicleModel.Premier] = 4,
        [VehicleModel.Enforcer] = 4,
        [VehicleModel.Securicar] = 4,
        [VehicleModel.Banshee] = 2,
        [VehicleModel.Predator] = 0,
        [VehicleModel.Bus] = 1,
        [VehicleModel.Rhino] = 1,
        [VehicleModel.Barracks] = 2,
        [VehicleModel.Hotknife] = 2,
        [VehicleModel.Trailer1] = 2,
        [VehicleModel.Previon] = 4,
        [VehicleModel.Coach] = 1,
        [VehicleModel.Cabbie] = 4,
        [VehicleModel.Stallion] = 4,
        [VehicleModel.Rumpo] = 4,
        [VehicleModel.RCBandit] = 0,
        [VehicleModel.Romero] = 4,
        [VehicleModel.Packer] = 2,
        [VehicleModel.Monster] = 2,
        [VehicleModel.Admiral] = 4,
        [VehicleModel.Squalo] = 0,
        [VehicleModel.Seasparrow] = 2,
        [VehicleModel.Pizzaboy] = 0,
        [VehicleModel.Tram] = 0,
        [VehicleModel.Trailer2] = 2,
        [VehicleModel.Turismo] = 2,
        [VehicleModel.Speeder] = 0,
        [VehicleModel.Reefer] = 0,
        [VehicleModel.Tropic] = 0,
        [VehicleModel.Flatbed] = 2,
        [VehicleModel.Yankee] = 2,
        [VehicleModel.Caddy] = 0,
        [VehicleModel.Solair] = 4,
        [VehicleModel.BerkleysRCVan] = 4,
        [VehicleModel.Skimmer] = 2,
        [VehicleModel.PCJ600] = 0,
        [VehicleModel.Faggio] = 0,
        [VehicleModel.Freeway] = 0,
        [VehicleModel.RCBaron] = 0,
        [VehicleModel.RCRaider] = 0,
        [VehicleModel.Glendale] = 4,
        [VehicleModel.Oceanic] = 4,
        [VehicleModel.Sanchez] = 0,
        [VehicleModel.Sparrow] = 2,
        [VehicleModel.Patriot] = 4,
        [VehicleModel.Quadbike] = 0,
        [VehicleModel.Coastguard] = 0,
        [VehicleModel.Dinghy] = 0,
        [VehicleModel.Hermes] = 4,
        [VehicleModel.Sabre] = 4,
        [VehicleModel.Rustler] = 1,
        [VehicleModel.ZR350] = 2,
        [VehicleModel.Walton] = 4,
        [VehicleModel.Regina] = 4,
        [VehicleModel.Comet] = 2,
        [VehicleModel.BMX] = 0,
        [VehicleModel.Burrito] = 4,
        [VehicleModel.Camper] = 2,
        [VehicleModel.Marquis] = 0,
        [VehicleModel.Baggage] = 0,
        [VehicleModel.Dozer] = 0,
        [VehicleModel.Maverick] = 4,
        [VehicleModel.NewsChopper] = 4,
        [VehicleModel.Rancher] = 2,
        [VehicleModel.FBIRancher] = 4,
        [VehicleModel.Virgo] = 4,
        [VehicleModel.Greenwood] = 4,
        [VehicleModel.Jetmax] = 0,
        [VehicleModel.HotringRacer] = 4,
        [VehicleModel.Sandking] = 2,
        [VehicleModel.BlistaCompact] = 2,
        [VehicleModel.PoliceMaverick] = 4,
        [VehicleModel.Boxville] = 4,
        [VehicleModel.Benson] = 4,
        [VehicleModel.Mesa] = 4,
        [VehicleModel.RCGoblin] = 0,
        [VehicleModel.HotringRacer3] = 2,
        [VehicleModel.HotringRacer2] = 2,
        [VehicleModel.BloodringBanger] = 0,
        [VehicleModel.RancherLure] = 2,
        [VehicleModel.SuperGT] = 2,
        [VehicleModel.Elegant] = 4,
        [VehicleModel.Journey] = 4,
        [VehicleModel.Bike] = 0,
        [VehicleModel.MountainBike] = 0,
        [VehicleModel.Beagle] = 2,
        [VehicleModel.Cropduster] = 1,
        [VehicleModel.Stuntplane] = 1,
        [VehicleModel.Tanker] = 2,
        [VehicleModel.Roadtrain] = 2,
        [VehicleModel.Nebula] = 4,
        [VehicleModel.Majestic] = 4,
        [VehicleModel.Buccaneer] = 4,
        [VehicleModel.Shamal] = 1,
        [VehicleModel.Hydra] = 1,
        [VehicleModel.FCR900] = 0,
        [VehicleModel.NRG500] = 0,
        [VehicleModel.HPV1000] = 0,
        [VehicleModel.CementTruck] = 2,
        [VehicleModel.Towtruck] = 2,
        [VehicleModel.Fortune] = 4,
        [VehicleModel.Cadrona] = 4,
        [VehicleModel.FBITruck] = 4,
        [VehicleModel.Willard] = 4,
        [VehicleModel.Forklift] = 0,
        [VehicleModel.Tractor] = 0,
        [VehicleModel.CombineHarvester] = 1,
        [VehicleModel.Feltzer] = 2,
        [VehicleModel.Remington] = 4,
        [VehicleModel.Slamvan] = 2,
        [VehicleModel.Blade] = 2,
        [VehicleModel.Freight] = 0,
        [VehicleModel.Streak] = 0,
        [VehicleModel.Vortex] = 0,
        [VehicleModel.Vincent] = 4,
        [VehicleModel.Bullet] = 2,
        [VehicleModel.Clover] = 4,
        [VehicleModel.Sadler] = 2,
        [VehicleModel.FireTruckLadder] = 2,
        [VehicleModel.Hustler] = 2,
        [VehicleModel.Intruder] = 4,
        [VehicleModel.Primo] = 4,
        [VehicleModel.Cargobob] = 2,
        [VehicleModel.Tampa] = 2,
        [VehicleModel.Sunrise] = 4,
        [VehicleModel.Merit] = 4,
        [VehicleModel.UtilityVan] = 2,
        [VehicleModel.Nevada] = 4,
        [VehicleModel.Yosemite] = 4,
        [VehicleModel.Windsor] = 2,
        [VehicleModel.Monster2] = 2,
        [VehicleModel.Monster3] = 2,
        [VehicleModel.Uranus] = 4,
        [VehicleModel.Jester] = 4,
        [VehicleModel.Sultan] = 4,
        [VehicleModel.Stratum] = 4,
        [VehicleModel.Elegy] = 2,
        [VehicleModel.Raindance] = 2,
        [VehicleModel.RCTiger] = 0,
        [VehicleModel.Flash] = 4,
        [VehicleModel.Tahoma] = 4,
        [VehicleModel.Savanna] = 2,
        [VehicleModel.Bandito] = 0,
        [VehicleModel.FreightTrainFlatbed] = 0,
        [VehicleModel.StreakTrainTrailer] = 0,
        [VehicleModel.Kart] = 0,
        [VehicleModel.Mower] = 0,
        [VehicleModel.Dune] = 2,
        [VehicleModel.Sweeper] = 4,
        [VehicleModel.Broadway] = 2,
        [VehicleModel.Tornado] = 4,
        [VehicleModel.AT400] = 1,
        [VehicleModel.DFT30] = 2,
        [VehicleModel.Huntley] = 4,
        [VehicleModel.Stafford] = 4,
        [VehicleModel.BF400] = 0,
        [VehicleModel.Newsvan] = 4,
        [VehicleModel.Tug] = 1,
        [VehicleModel.TrailerTankerCommando] = 2,
        [VehicleModel.Emperor] = 4,
        [VehicleModel.Wayfarer] = 0,
        [VehicleModel.Euros] = 4,
        [VehicleModel.Hotdog] = 2,
        [VehicleModel.Club] = 2,
        [VehicleModel.BoxFreight] = 0,
        [VehicleModel.Trailer3] = 2,
        [VehicleModel.Andromada] = 1,
        [VehicleModel.Dodo] = 2,
        [VehicleModel.RCCam] = 1,
        [VehicleModel.Launch] = 1,
        [VehicleModel.PoliceLS] = 4,
        [VehicleModel.PoliceSf] = 4,
        [VehicleModel.PoliceLV] = 4,
        [VehicleModel.PoliceRanger] = 2,
        [VehicleModel.Picador] = 2,
        [VehicleModel.SwatTank] = 2,
        [VehicleModel.Alpha] = 2,
        [VehicleModel.Phoenix] = 2,
        [VehicleModel.GlendaleDamaged] = 4,
        [VehicleModel.SadlerDamaged] = 2,
        [VehicleModel.BaggageTrailerCovered] = 2,
        [VehicleModel.BaggageTrailerUncovered] = 2,
        [VehicleModel.TrailerStairs] = 2,
        [VehicleModel.FarmTrailer] = 2,
        [VehicleModel.FarmTrailerTwo] = 2
    };

    public static Dictionary<VehicleModel, byte> SeatsPerVehicle { get; } = new()
    {
        [VehicleModel.Landstalker] = 4,
        [VehicleModel.Bravura] = 4,
        [VehicleModel.Buffalo] = 4,
        [VehicleModel.Linerunner] = 4,
        [VehicleModel.Perennial] = 4,
        [VehicleModel.Sentinel] = 4,
        [VehicleModel.Dumper] = 1,
        [VehicleModel.FireTruck] = 2,
        [VehicleModel.Trashmaster] = 2,
        [VehicleModel.Stretch] = 4,
        [VehicleModel.Manana] = 2,
        [VehicleModel.Infernus] = 2,
        [VehicleModel.Voodoo] = 4,
        [VehicleModel.Pony] = 4,
        [VehicleModel.Mule] = 4,
        [VehicleModel.Cheetah] = 2,
        [VehicleModel.Ambulance] = 4,
        [VehicleModel.Leviathan] = 2,
        [VehicleModel.Moonbeam] = 4,
        [VehicleModel.Esperanto] = 4,
        [VehicleModel.Taxi] = 4,
        [VehicleModel.Washington] = 4,
        [VehicleModel.Bobcat] = 2,
        [VehicleModel.MrWhoopee] = 2,
        [VehicleModel.BFInjection] = 2,
        [VehicleModel.Hunter] = 1,
        [VehicleModel.Premier] = 4,
        [VehicleModel.Enforcer] = 4,
        [VehicleModel.Securicar] = 4,
        [VehicleModel.Banshee] = 2,
        [VehicleModel.Predator] = 1,
        [VehicleModel.Bus] = 1,
        [VehicleModel.Rhino] = 1,
        [VehicleModel.Barracks] = 2,
        [VehicleModel.Hotknife] = 2,
        [VehicleModel.Trailer1] = 0,
        [VehicleModel.Previon] = 4,
        [VehicleModel.Coach] = 1,
        [VehicleModel.Cabbie] = 4,
        [VehicleModel.Stallion] = 4,
        [VehicleModel.Rumpo] = 4,
        [VehicleModel.RCBandit] = 1,
        [VehicleModel.Romero] = 4,
        [VehicleModel.Packer] = 2,
        [VehicleModel.Monster] = 2,
        [VehicleModel.Admiral] = 4,
        [VehicleModel.Squalo] = 1,
        [VehicleModel.Seasparrow] = 2,
        [VehicleModel.Pizzaboy] = 2,
        [VehicleModel.Tram] = 0,
        [VehicleModel.Trailer2] = 0,
        [VehicleModel.Turismo] = 2,
        [VehicleModel.Speeder] = 1,
        [VehicleModel.Reefer] = 1,
        [VehicleModel.Tropic] = 1,
        [VehicleModel.Flatbed] = 2,
        [VehicleModel.Yankee] = 2,
        [VehicleModel.Caddy] = 2,
        [VehicleModel.Solair] = 4,
        [VehicleModel.BerkleysRCVan] = 4,
        [VehicleModel.Skimmer] = 2,
        [VehicleModel.PCJ600] = 2,
        [VehicleModel.Faggio] = 2,
        [VehicleModel.Freeway] = 2,
        [VehicleModel.RCBaron] = 1,
        [VehicleModel.RCRaider] = 0,
        [VehicleModel.Glendale] = 4,
        [VehicleModel.Oceanic] = 4,
        [VehicleModel.Sanchez] = 1,
        [VehicleModel.Sparrow] = 2,
        [VehicleModel.Patriot] = 4,
        [VehicleModel.Quadbike] = 1,
        [VehicleModel.Coastguard] = 1,
        [VehicleModel.Dinghy] = 0,
        [VehicleModel.Hermes] = 4,
        [VehicleModel.Sabre] = 4,
        [VehicleModel.Rustler] = 1,
        [VehicleModel.ZR350] = 2,
        [VehicleModel.Walton] = 4,
        [VehicleModel.Regina] = 4,
        [VehicleModel.Comet] = 2,
        [VehicleModel.BMX] = 1,
        [VehicleModel.Burrito] = 4,
        [VehicleModel.Camper] = 2,
        [VehicleModel.Marquis] = 1,
        [VehicleModel.Baggage] = 1,
        [VehicleModel.Dozer] = 1,
        [VehicleModel.Maverick] = 4,
        [VehicleModel.NewsChopper] = 4,
        [VehicleModel.Rancher] = 2,
        [VehicleModel.FBIRancher] = 4,
        [VehicleModel.Virgo] = 4,
        [VehicleModel.Greenwood] = 4,
        [VehicleModel.Jetmax] = 1,
        [VehicleModel.HotringRacer] = 4,
        [VehicleModel.Sandking] = 2,
        [VehicleModel.BlistaCompact] = 2,
        [VehicleModel.PoliceMaverick] = 4,
        [VehicleModel.Boxville] = 4,
        [VehicleModel.Benson] = 4,
        [VehicleModel.Mesa] = 4,
        [VehicleModel.RCGoblin] = 1,
        [VehicleModel.HotringRacer3] = 2,
        [VehicleModel.HotringRacer2] = 2,
        [VehicleModel.BloodringBanger] = 2,
        [VehicleModel.RancherLure] = 2,
        [VehicleModel.SuperGT] = 2,
        [VehicleModel.Elegant] = 4,
        [VehicleModel.Journey] = 4,
        [VehicleModel.Bike] = 1,
        [VehicleModel.MountainBike] = 1,
        [VehicleModel.Beagle] = 2,
        [VehicleModel.Cropduster] = 1,
        [VehicleModel.Stuntplane] = 1,
        [VehicleModel.Tanker] = 2,
        [VehicleModel.Roadtrain] = 2,
        [VehicleModel.Nebula] = 4,
        [VehicleModel.Majestic] = 4,
        [VehicleModel.Buccaneer] = 4,
        [VehicleModel.Shamal] = 1,
        [VehicleModel.Hydra] = 1,
        [VehicleModel.FCR900] = 2,
        [VehicleModel.NRG500] = 2,
        [VehicleModel.HPV1000] = 2,
        [VehicleModel.CementTruck] = 2,
        [VehicleModel.Towtruck] = 2,
        [VehicleModel.Fortune] = 4,
        [VehicleModel.Cadrona] = 4,
        [VehicleModel.FBITruck] = 4,
        [VehicleModel.Willard] = 4,
        [VehicleModel.Forklift] = 1,
        [VehicleModel.Tractor] = 1,
        [VehicleModel.CombineHarvester] = 1,
        [VehicleModel.Feltzer] = 2,
        [VehicleModel.Remington] = 4,
        [VehicleModel.Slamvan] = 2,
        [VehicleModel.Blade] = 2,
        [VehicleModel.Freight] = 2,
        [VehicleModel.Streak] = 2,
        [VehicleModel.Vortex] = 1,
        [VehicleModel.Vincent] = 4,
        [VehicleModel.Bullet] = 2,
        [VehicleModel.Clover] = 4,
        [VehicleModel.Sadler] = 2,
        [VehicleModel.FireTruckLadder] = 2,
        [VehicleModel.Hustler] = 2,
        [VehicleModel.Intruder] = 4,
        [VehicleModel.Primo] = 4,
        [VehicleModel.Cargobob] = 2,
        [VehicleModel.Tampa] = 2,
        [VehicleModel.Sunrise] = 4,
        [VehicleModel.Merit] = 4,
        [VehicleModel.UtilityVan] = 2,
        [VehicleModel.Nevada] = 4,
        [VehicleModel.Yosemite] = 4,
        [VehicleModel.Windsor] = 2,
        [VehicleModel.Monster2] = 2,
        [VehicleModel.Monster3] = 2,
        [VehicleModel.Uranus] = 4,
        [VehicleModel.Jester] = 4,
        [VehicleModel.Sultan] = 4,
        [VehicleModel.Stratum] = 4,
        [VehicleModel.Elegy] = 2,
        [VehicleModel.Raindance] = 2,
        [VehicleModel.RCTiger] = 1,
        [VehicleModel.Flash] = 4,
        [VehicleModel.Tahoma] = 4,
        [VehicleModel.Savanna] = 2,
        [VehicleModel.Bandito] = 1,
        [VehicleModel.FreightTrainFlatbed] = 2,
        [VehicleModel.StreakTrainTrailer] = 2,
        [VehicleModel.Kart] = 1,
        [VehicleModel.Mower] = 1,
        [VehicleModel.Dune] = 2,
        [VehicleModel.Sweeper] = 4,
        [VehicleModel.Broadway] = 2,
        [VehicleModel.Tornado] = 4,
        [VehicleModel.AT400] = 1,
        [VehicleModel.DFT30] = 2,
        [VehicleModel.Huntley] = 4,
        [VehicleModel.Stafford] = 4,
        [VehicleModel.BF400] = 2,
        [VehicleModel.Newsvan] = 4,
        [VehicleModel.Tug] = 1,
        [VehicleModel.TrailerTankerCommando] = 0,
        [VehicleModel.Emperor] = 4,
        [VehicleModel.Wayfarer] = 2,
        [VehicleModel.Euros] = 4,
        [VehicleModel.Hotdog] = 2,
        [VehicleModel.Club] = 2,
        [VehicleModel.BoxFreight] = 2,
        [VehicleModel.Trailer3] = 0,
        [VehicleModel.Andromada] = 1,
        [VehicleModel.Dodo] = 2,
        [VehicleModel.RCCam] = 1,
        [VehicleModel.Launch] = 1,
        [VehicleModel.PoliceLS] = 4,
        [VehicleModel.PoliceSf] = 4,
        [VehicleModel.PoliceLV] = 4,
        [VehicleModel.PoliceRanger] = 2,
        [VehicleModel.Picador] = 2,
        [VehicleModel.SwatTank] = 2,
        [VehicleModel.Alpha] = 2,
        [VehicleModel.Phoenix] = 2,
        [VehicleModel.GlendaleDamaged] = 4,
        [VehicleModel.SadlerDamaged] = 2,
        [VehicleModel.BaggageTrailerCovered] = 0,
        [VehicleModel.BaggageTrailerUncovered] = 0,
        [VehicleModel.TrailerStairs] = 0,
        [VehicleModel.FarmTrailer] = 0,
        [VehicleModel.FarmTrailerTwo] = 0
    };

    public static HashSet<VehicleModel> AdjustablePropertyModels { get; } = new()
    {
        VehicleModel.Dumper,
        VehicleModel.Packer,
        VehicleModel.Dozer,
        VehicleModel.Hydra,
        VehicleModel.Towtruck,
        VehicleModel.Forklift,
        VehicleModel.Tractor,
        VehicleModel.Andromada,
        VehicleModel.CementTruck,
    };

    public static HashSet<VehicleModel> TurretModels { get; } = new()
    {
        VehicleModel.FireTruck,
        VehicleModel.Rhino,
        VehicleModel.SwatTank,
    };
}
